

const attacks = [
  {
    name:     'WannaCry Ransomware',
    year:     '2017',
    type:     'Ransomware / Cryptoworm',
    actor:    'Lazarus Group (North Korea)',
    affected: '200,000+ systems in 150 countries',
    damage:   '$4–8 billion',
    severity: 'CRITICAL',
    desc: 'WannaCry was a global ransomware attack that targeted Windows machines by exploiting the EternalBlue SMB exploit leaked from the NSA. It spread automatically across networks without user interaction, encrypting files and demanding Bitcoin ransoms. The NHS in the UK was severely crippled, cancelling thousands of appointments and diverting ambulances.',
    flow: ['EternalBlue SMB Exploit', 'Worm Propagation', 'File Encryption', 'Ransom Demand', 'Bitcoin C2 Comm'],
    impact: ['$8B Damages', '150 Countries', '200K Systems'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [45, 22, 18, 10, 5],
    chartLabels: ['UK NHS', 'Russia Telco', 'Spain Telefónica', 'Germany DB', 'Others'],
    lessons: [
      'Patch systems promptly — MS17-010 patch was available 2 months before the attack.',
      'Disable unused SMBv1 protocol to reduce attack surface.',
      'Maintain offline backups to recover from ransomware without paying.',
      'Network segmentation prevents worm lateral movement across subnets.',
      'Threat intelligence sharing between nations is critical for APT attribution.',
    ]
  },
  {
    name:     'Target Data Breach',
    year:     '2013',
    type:     'POS Malware / Supply Chain',
    actor:    'Eastern European Cybercriminals',
    affected: '110 million customers',
    damage:   '$202 million total',
    severity: 'CRITICAL',
    desc: 'Attackers gained access to Target\'s network via a third-party HVAC vendor\'s stolen credentials. They installed custom POS malware called "BlackPOS" on payment terminals across 1,800+ stores. The malware captured card data from RAM before encryption, exposing 40M credit card numbers and 70M personal records during the busy holiday shopping season.',
    flow: ['Vendor Credential Theft', 'VPN Access to Target', 'POS Malware Install', 'RAM Scraping', 'Data Staging & Exfil'],
    impact: ['$202M Cost', '110M Records', '1800+ Stores'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [40, 30, 20, 10],
    chartLabels: ['Credit Cards', 'Debit Cards', 'Email Addresses', 'Phone Numbers'],
    lessons: [
      'Third-party vendor access must be tightly controlled and monitored.',
      'Network segmentation between POS systems and corporate networks is essential.',
      'Chip-and-PIN (EMV) technology prevents RAM scraping attacks on card terminals.',
      'Real-time anomaly detection could have caught the data staging before exfil.',
      'Least-privilege principle for vendor access limits blast radius of compromise.',
    ]
  },
  {
    name:     'SolarWinds SUNBURST',
    year:     '2020',
    type:     'Supply Chain APT',
    actor:    'APT29 / Cozy Bear (Russia SVR)',
    affected: '18,000+ organizations incl. US Gov',
    damage:   '$100 billion estimated',
    severity: 'CRITICAL',
    desc: 'Nation-state attackers compromised SolarWinds\'s build pipeline and injected the SUNBURST backdoor into Orion IT monitoring software updates. The trojanized update was signed with legitimate certificates and distributed to 18,000+ customers. Attackers gained persistent, stealthy access to agencies including Treasury, DHS, Pentagon, and Fortune 500 companies for over 9 months undetected.',
    flow: ['Build System Compromise', 'Trojanized Update', 'Code Signing', 'Software Deployment', 'Dormant (2wk)', 'C2 Activation'],
    impact: ['18K Organizations', '9 US Agencies', '$100B Impact'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [35, 30, 20, 15],
    chartLabels: ['US Government', 'Defense Contractors', 'Tech Companies', 'Financial'],
    lessons: [
      'Software supply chain integrity must be verified — sign all build artifacts.',
      'Code signing alone is insufficient without build process integrity monitoring.',
      'Implement zero-trust principles even for trusted software vendors.',
      'Behavioral analytics can detect C2 beaconing patterns during dormancy.',
      'Privileged access management reduces impact when monitoring tools are compromised.',
    ]
  },
  {
    name:     'Mirai Botnet DDoS',
    year:     '2016',
    type:     'IoT Botnet / DDoS',
    actor:    'Paras Jha & Associates',
    affected: 'Dyn DNS, GitHub, Twitter, Netflix',
    damage:   'Hundreds of millions',
    severity: 'HIGH',
    desc: 'Mirai malware scanned the internet for IoT devices with default credentials (routers, cameras, DVRs) and conscripted them into a botnet of 600,000+ devices. This botnet was used to launch record-breaking DDoS attacks peaking at 1.2 Tbps against Dyn DNS, taking down major portions of the internet across the US and Europe for hours.',
    flow: ['Default Credential Scan', 'IoT Device Compromise', 'Botnet C2 Setup', 'Coordinated DDoS', 'DNS Amplification'],
    impact: ['1.2 Tbps Peak', '600K Bots', 'Internet Outage'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [40, 25, 20, 15],
    chartLabels: ['IP Cameras', 'DVRs', 'Routers', 'Smart TVs'],
    lessons: [
      'IoT manufacturers must enforce unique default passwords per device at factory.',
      'ISPs should implement BCP38 to prevent IP spoofing used in amplification attacks.',
      'Anycast DNS and CDN redundancy reduces DDoS impact on DNS infrastructure.',
      'Network-level rate limiting and traffic scrubbing centers are essential defenses.',
      'Botnet takedowns require coordinated law enforcement and ISP cooperation.',
    ]
  },
  {
    name:     'Heartbleed (OpenSSL)',
    year:     '2014',
    type:     'Cryptographic Vulnerability',
    actor:    'Unknown (independently discovered)',
    affected: '17% of all HTTPS servers',
    damage:   '500 million+ records at risk',
    severity: 'CRITICAL',
    desc: 'CVE-2014-0160 was a buffer over-read bug in OpenSSL\'s TLS heartbeat extension. Attackers could send a malformed heartbeat request causing servers to return up to 64KB of server memory per request — containing private SSL keys, session tokens, passwords, or any sensitive data in memory — all without leaving any trace in server logs.',
    flow: ['Send Malformed Heartbeat', 'Memory Over-read (64KB)', 'Extract Private Keys', 'Decrypt Past Traffic', 'Session Hijacking'],
    impact: ['17% of Internet', '2yr Undetected', '0 Log Traces'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [30, 25, 20, 15, 10],
    chartLabels: ['Web Servers', 'VPN Gateways', 'Email Servers', 'DB Proxies', 'Others'],
    lessons: [
      'Implement automated vulnerability scanning in your software supply chain.',
      'Certificate revocation and reissue procedures must be practiced regularly.',
      'Perfect Forward Secrecy (PFS) limits the impact of private key compromise.',
      'Memory-safe languages (Rust, Go) eliminate entire classes of buffer vulnerabilities.',
      'Responsible disclosure programs accelerate patching of critical open source.',
    ]
  },
  {
    name:     'Colonial Pipeline Attack',
    year:     '2021',
    type:     'Ransomware / Critical Infrastructure',
    actor:    'DarkSide (Russia-linked)',
    affected: 'US East Coast fuel supply',
    damage:   '$4.4M ransom + economic disruption',
    severity: 'CRITICAL',
    desc: 'DarkSide ransomware group accessed Colonial Pipeline\'s IT network via a compromised VPN account with no MFA enabled. They stole 100GB of data then deployed ransomware encrypting billing and business systems. Colonial proemptively shut down OT/pipeline operations, causing fuel shortages across the US East Coast, state of emergency declarations, and widespread gas station panic buying.',
    flow: ['Stolen VPN Credentials', 'No MFA — Access Gained', 'Data Exfiltration (100GB)', 'Ransomware Deployment', 'Pipeline Shutdown'],
    impact: ['5,500 Miles Pipeline', '$4.4M Ransom', 'Fuel Shortage Crisis'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [45, 30, 25],
    chartLabels: ['IT Systems Down', 'OT/SCADA Impact', 'Business Disruption'],
    lessons: [
      'Multi-factor authentication must be mandatory for all remote access — no exceptions.',
      'IT and OT networks must be strictly air-gapped to prevent ransomware spread.',
      'Critical infrastructure operators need incident response plans tested regularly.',
      'Segmented offline backups enable faster recovery without paying ransoms.',
      'Government-private sector threat intel sharing is essential for ICS/OT security.',
    ]
  },
  {
    name:     'Lapsus$ Extortion Gang',
    year:     '2022',
    type:     'Social Engineering / Insider Threat',
    actor:    'Lapsus$ (Teenagers, UK/Brazil)',
    affected: 'Nvidia, Samsung, Okta, Microsoft',
    damage:   'Billions in IP theft',
    severity: 'HIGH',
    desc: 'Lapsus$ was a loosely organized extortion group primarily composed of teenagers who bypassed sophisticated security controls through social engineering. They bribed or recruited insiders, used SIM swapping to defeat MFA, and purchased credentials from criminal markets. They breached Nvidia, Samsung, Microsoft, Uber, and Rockstar Games — exfiltrating source code and unreleased content.',
    flow: ['Insider Recruitment', 'SIM Swap MFA Bypass', 'Credential Markets', 'Source Code Access', 'Public Extortion'],
    impact: ['8+ Major Corps', 'Source Code Theft', 'Teen Perpetrators'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [35, 25, 20, 20],
    chartLabels: ['Insider Recruitment', 'SIM Swapping', 'Credential Stuffing', 'Phishing'],
    lessons: [
      'Phishing-resistant MFA (hardware keys) defeats SIM swapping attacks entirely.',
      'Insider threat programs must detect unusual data access and download patterns.',
      'Data loss prevention (DLP) tools block large-scale source code exfiltration.',
      'Vetting and monitoring contractors is as important as monitoring full-time employees.',
      'Zero-trust architecture limits damage even when an identity is fully compromised.',
    ]
  },
  {
    name:     'MOVEit Transfer Breach',
    year:     '2023',
    type:     'Zero-Day / SQL Injection',
    actor:    'Cl0p Ransomware Group',
    affected: '2,500+ organizations globally',
    damage:   '$9.9 billion estimated',
    severity: 'CRITICAL',
    desc: 'The Cl0p ransomware group exploited a critical SQL injection zero-day (CVE-2023-34362) in Progress Software\'s MOVEit Transfer file-transfer product. The flaw allowed unauthenticated attackers to access and exfiltrate data. Major victims included the US Department of Energy, British Airways, BBC, Shell, and hundreds of universities and government agencies worldwide.',
    flow: ['Zero-Day Discovery', 'SQL Injection Exploit', 'Webshell Deployment', 'Mass Data Exfiltration', 'Extortion Campaign'],
    impact: ['2,500+ Orgs', '$9.9B Estimated', '95M Records'],
    impactColors: ['var(--accent2)', 'var(--warn)', 'var(--accent3)'],
    chartData:   [30, 25, 22, 23],
    chartLabels: ['Government', 'Finance', 'Healthcare', 'Education'],
    lessons: [
      'Apply emergency patches to internet-facing file transfer tools within hours, not days.',
      'Audit all managed file transfer software for known and unknown vulnerabilities.',
      'Restrict network access to file transfer portals using IP allowlisting.',
      'Implement data-at-rest encryption so exfiltrated files are useless without keys.',
      'Third-party risk assessments must include all software used for sensitive data transfer.',
    ]
  }
];
